
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'PNUMBER EQUALS NEWLINE NORMALSTRINGdescription : PNUMBER EQUALS string newlinestring : NORMALSTRING\n                  | string NORMALSTRINGnewline : NEWLINE'
    
_lr_action_items = {'NEWLINE':([4,5,8,],[-2,7,-3,]),'PNUMBER':([0,],[1,]),'EQUALS':([1,],[3,]),'NORMALSTRING':([3,4,5,8,],[4,-2,8,-3,]),'$end':([2,6,7,],[0,-1,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'newline':([5,],[6,]),'description':([0,],[2,]),'string':([3,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> description","S'",1,None,None,None),
  ('description -> PNUMBER EQUALS string newline','description',4,'p_description','atfyacc.py',12),
  ('string -> NORMALSTRING','string',1,'p_string','atfyacc.py',16),
  ('string -> string NORMALSTRING','string',2,'p_string','atfyacc.py',17),
  ('newline -> NEWLINE','newline',1,'p_newline','atfyacc.py',21),
]
