
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMPERSAND ATF CBS COLON DEF DOLLAR EQUALS HASH LANG LEXICAL LINK NEWLINE PNUMBER QNUMBER STRING USE VERSION VNUMBERversion_comment : VERSION VNUMBER newlinestring : STRING\n                  | string STRING\n                  | string EQUALSnewline : NEWLINE'
    
_lr_action_items = {'NEWLINE':([3,],[4,]),'VNUMBER':([2,],[3,]),'VERSION':([0,],[2,]),'$end':([1,4,5,],[0,-5,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'version_comment':([0,],[1,]),'newline':([3,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> version_comment","S'",1,None,None,None),
  ('version_comment -> VERSION VNUMBER newline','version_comment',3,'p_version_comment','atfyacc.py',39),
  ('string -> STRING','string',1,'p_string','atfyacc.py',43),
  ('string -> string STRING','string',2,'p_string','atfyacc.py',44),
  ('string -> string EQUALS','string',2,'p_string','atfyacc.py',45),
  ('newline -> NEWLINE','newline',1,'p_newline','atfyacc.py',52),
]
